"""empty message

Revision ID: a8066cc12a92
Revises: 
Create Date: 2026-05-03 15:09:51.703406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8066cc12a92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=250), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_is_completed'), ['is_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_task'), ['task'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_timestamp'))
        batch_op.drop_index(batch_op.f('ix_todo_task'))
        batch_op.drop_index(batch_op.f('ix_todo_is_completed'))

    op.drop_table('todo')
    # ### end Alembic commands ###
